[package]
name = "random_forest_rust"
version = "0.1.0"
authors = ["shenjianwei <shenjianwei@xindong.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
