#[role]

ti = false 
party_id = 0

#[option]

debug_output = true
raw_tcp_communication = false

#[network]

ti_ip     = "127.0.0.1"
ti_port0  = 4000
ti_port1  = 8000

party0_ip   = "127.0.0.1"
party0_port = 5000

party1_ip   = "127.0.0.1"
party1_port = 6000

#[message_queue]
local_mq_ip = "127.0.0.1"
local_mq_port = 5672

remote_mq_ip = "127.0.0.1"
remote_mq_port = 5673

#[LOGISTIC REGRESSION]

decimal_precision = 10
integer_precision = 15 
learning_rate = 0.001

#[RANDOM FOREST]
tree_count = 1
thread_count = 40
max_depth = 1
alpha = 8
epsilon = 0.1

#[BREAST CANCER]
#batch_size = 176
#tree_training_batch_size = 20
#attr_value_count = 10
#class_value_count = 2
#attribute_count = 30
#instance_count = 100
#asymmetric_bit = 0
#prime = 512
#big_int_prime = "47890485652059026823698344598447161988085597568237568"
#dataset_size_prime = 512
#big_int_ti_index = 0
#bit_length = 175
#x_input_path = "/Users/sjw/Projects/2019summer/idash2019/breast_cancer/shared_fold_1_train-0.csv"
#output_path = "/Users/sjw/Desktop/PPML/idash/secure-mpc-rust/weights/BC_TCGA_5_folds/fold_1_weights.csv"

#[RANDOM DATA]
batch_size = 34
tree_training_batch_size = 20
attr_value_count = 2
class_value_count = 2
attribute_count = 3
instance_count = 5
asymmetric_bit = 0
prime = 8
big_int_prime = "8589934592"
dataset_size_prime = 8
big_int_ti_index = 0
bit_length = 33
x_input_path = "/Users/sjw/Desktop/PPML/preprocess/james/shared_fold_1_train-1.csv"
output_path = "/Users/sjw/Desktop/PPML/preprocess/james/fold_1_trees.csv"

#[GSE2034]

#x_input_path = "inputs/GSE2034_5_folds/5X_train_share0.csv"
#y_input_path = "inputs/GSE2034_5_folds/5y_train_share0.csv"
#output_path = "weights/GSE2034_5_folds/fold_5_weights.csv"
#attribute_count = 12634
#instance_count = 179
#iterations = 223
#add_shares_per_iter = 4526552
#xor_shares_per_iter = 3620
