#[role]

ti = false 
party_id = 1
asymmetric_bit = 1

#[option]

debug_output = false
test_mode = 1
raw_tcp_communication = true

#[network]

ti_ip     = "127.0.0.1"
ti_port0  = 4000
ti_port1  = 8000

party0_ip   = "127.0.0.1"
party0_port = 5000

party1_ip   = "127.0.0.1"
party1_port = 6000

#[message_queue]
local_mq_ip = "127.0.0.1"
local_mq_port = 5673

remote_mq_ip = "127.0.0.1"
remote_mq_port = 5672

#[LOGISTIC REGRESSION] 

decimal_precision = 10
integer_precision = 15
learning_rate = 0.001

#[RANDOM FOREST]
tree_count = 1
thread_count = 5
max_depth = 2
alpha = 8
epsilon = 0.1
ohe_add_shares = 1
ohe_binary_shares = 1
ohe_equality_shares = 1

#[BREAST CANCER]
instance_selected = 455
feature_selected = 30
batch_size = 153
tree_training_batch_size = 20
attr_value_count = 5
class_value_count = 2
attribute_count = 30
instance_count = 455
prime = 512
big_int_prime = "11417981541647680000000000000000000000000000319"
dataset_size_prime = 32
big_int_ti_index = 0
bit_length = 153
x_input_path = "/Users/sjw/Desktop/PPML/random forest/data/discretized_shared/breast_cancer/shared/trainX_shared_fold1_1.csv"
y_input_path = "/Users/sjw/Desktop/PPML/random forest/data/discretized_shared/breast_cancer/shared/trainy_shared_fold1_1.csv"
output_path = "breast_cancer_results/fold1/"

#instance_selected = 21
#feature_selected = 5
#batch_size = 84
#tree_training_batch_size = 20
#attr_value_count = 4
#class_value_count = 2
#attribute_count = 30
#instance_count = 456
#asymmetric_bit = 1
#prime = 32
#big_int_prime = "9671406556917033397649483"
#dataset_size_prime = 32
#big_int_ti_index = 0
#bit_length = 83
#x_input_path = "/home/ec2-user/rf_training/discretized_shared/breast_cancer/shared/trainX_shared_fold1_1.csv"
#y_input_path = "/home/ec2-user/rf_training/discretized_shared/breast_cancer/shared/trainy_shared_fold1_1.csv"
#output_path = "/home/ec2-user/rf_training/breast_cancer/fold1/"

#[ECG Heartbeat]
#instance_selected = 121
#feature_selected = 14
#batch_size = 106
#tree_training_batch_size = 20
#attr_value_count = 4
#class_value_count = 2
#attribute_count = 188
#instance_count = 11641
#prime = 128
#big_int_prime = "40564819207303340847894502572071"
#dataset_size_prime = 32
#big_int_ti_index = 0
#bit_length = 105
#x_input_path = "/Users/sjw/Desktop/PPML/random forest/data/discretized_shared/pt_data/shared/trainX_shared_fold2_1.csv"
#y_input_path = "/Users/sjw/Desktop/PPML/random forest/data/discretized_shared/pt_data/shared/trainy_shared_fold2_1.csv"
#output_path = "ECG/fold2/"

#[RANDOM DATA]
#instance_selected = 4
#feature_selected = 3
#batch_size = 26
#tree_training_batch_size = 20
#attr_value_count = 2
#class_value_count = 2
#attribute_count = 3
#instance_count = 4
#prime = 4
#big_int_prime = "67108879"
#dataset_size_prime = 4
#big_int_ti_index = 0
#bit_length = 26
#x_input_path = "/Users/sjw/Projects/random_forest_rust/test_data/trainX3_1.csv"
#y_input_path = "/Users/sjw/Projects/random_forest_rust/test_data/trainy3_1.csv"
#output_path = "test_data/fold1/"

#[GSE2034]

#x_input_path = "inputs/GSE2034_5_folds/5X_train_share1.csv"
#y_input_path = "inputs/GSE2034_5_folds/5y_train_share1.csv"
#output_path = "weights/GSE2034_5_folds/fold_5_weights.csv"
#attribute_count = 12634
#instance_count = 179
#iterations = 223
#add_shares_per_iter = 4526552
#xor_shares_per_iter = 3620
