#[role]

ti = true

#[network]

ti_ip     = "127.0.0.1"
ti_port0  = 4000
ti_port1  = 8000

#[random forest]
tree_count = 100
tree_training_batch_size = 20
thread_count = 40


#[breast Cancer]
batch_size = 176
add_shares_per_tree = 1000
add_shares_bigint_per_tree = 1000
equality_shares_per_tree = 1000
binary_shares_per_tree = 1000
ohe_add_shares = 1000
ohe_binary_shares = 1000
ohe_equality_shares = 1000
big_int_prime = "47890485652059026823698344598447161988085597568237568"
prime = 512
bigint_bit_size = 175
attr_value_cnt = 6
class_value_cnt = 2
feature_selected = 5
instance_selected = 21
instance_cnt = 455
feature_cnt = 30



#[random data]
#batch_size = 34
#add_shares_per_tree = 1000
#add_shares_bigint_per_tree = 1000
#equality_shares_per_tree = 1000
#binary_shares_per_tree = 10000
#ohe_add_shares = 1000
#ohe_binary_shares = 1000
#ohe_equality_shares = 1000
#big_int_prime = "8589934592"
#prime = 8
#bigint_bit_size = 33
#attr_value_cnt = 2
#class_value_cnt = 2
#feature_selected = 2
#instance_selected = 3
#instance_cnt = 4
#feature_cnt = 3

#[BC-TCGA]

#iterations = 10
#add_shares_per_iter = 13368000
#xor_shares_per_iter = 7512

#[GSE2034]

#iterations = 223
#add_shares_per_iter = 4526552
#xor_shares_per_iter = 3620


