test_mode = 1
feature_selected = 5
tree_count = 100
max_depth = 1
instance_cnt = 455
instance_selected = 455
feature_cnt = 30
attr_value_cnt = 5
output_path = "breast_cancer_results/fold1/"
#output_path = "C:/Users/Sam/Documents/rf/settings/breast_results/fold1/"
batch_size = 153

#[role]

ti = true

#[network]

ti_ip     = "127.0.0.1"
ti_port0  = 4000
ti_port1  = 8000

#[random forest]
#tree_count = 100
tree_training_batch_size = 20
thread_count = 16


#[breast Cancer]
#batch_size = 84
add_shares_per_tree = 1
add_shares_bigint_per_tree = 1
equality_shares_per_tree = 1
binary_shares_per_tree = 1
ohe_add_shares = 1
ohe_binary_shares = 1
ohe_equality_shares = 1
big_int_prime = "11417981541647680000000000000000000000000000319"
prime = 512
bigint_bit_size = 153
#attr_value_cnt = 4
class_value_cnt = 2
#feature_selected = 5
#instance_selected = 21
#instance_cnt = 11642
#feature_cnt = 187
#output_path = "C:/Users/david/Desktop/RUST_XT/rf/settings/ecg_results/"

#batch_size = 84
#add_shares_per_tree = 1000
#add_shares_bigint_per_tree = 1000
#equality_shares_per_tree = 1000
#binary_shares_per_tree = 1000
#ohe_add_shares = 1000
#ohe_binary_shares = 1000
#ohe_equality_shares = 1000
#big_int_prime = "9671406556917033397649483"
#prime = 32
#bigint_bit_size = 83
#attr_value_cnt = 4
#class_value_cnt = 2
#feature_selected = 5
#instance_selected = 21
#instance_cnt = 456
#feature_cnt = 30
#output_path = "breast_cancer_results/fold5/"

#[ECG Heartbeat]
#batch_size = 106
#add_shares_per_tree = 1000
#add_shares_bigint_per_tree = 1000
#equality_shares_per_tree = 1000
#binary_shares_per_tree = 1000
#ohe_add_shares = 1000
#ohe_binary_shares = 1000
#ohe_equality_shares = 1000
#big_int_prime = "40564819207303340847894502572071"
#prime = 128
#bigint_bit_size = 105
#attr_value_cnt = 4
#class_value_cnt = 2
#feature_selected = 14
#instance_selected = 121
#instance_cnt = 11641
#feature_cnt = 188
#output_path = "ECG/fold2/"

#[random data]
#batch_size = 34
#add_shares_per_tree = 1000
#add_shares_bigint_per_tree = 1000
#equality_shares_per_tree = 1000
#binary_shares_per_tree = 10000
#ohe_add_shares = 1000
#ohe_binary_shares = 1000
#ohe_equality_shares = 1000
#big_int_prime = "8589934592"
#prime = 8
#bigint_bit_size = 33
#attr_value_cnt = 2
#class_value_cnt = 2
#feature_selected = 2
#instance_selected = 3
#instance_cnt = 4
#feature_cnt = 3
#output_path = "breast_cancer_results/fold1/"

#[BC-TCGA]

#iterations = 10
#add_shares_per_iter = 13368000
#xor_shares_per_iter = 7512

#[GSE2034]

#iterations = 223
#add_shares_per_iter = 4526552
#xor_shares_per_iter = 3620


