[package]
name = "party"
version = "0.1.0"
authors = ["James Shen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = {"version"="0.1",path="../utils/"}
communicator = {"version"="0.1",path="../communicator/"}
